use_frameworks!

target 'CocoaPodsRegTest_Example' do
  pod 'CocoaPodsRegTest', :path => '../'

  target 'CocoaPodsRegTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
